"""Model interface protocols. The residual layer is swappable (SGD ↔ LGBM ↔ ...)."""

from typing import Protocol, runtime_checkable

import numpy as np


@runtime_checkable
class BaseModel(Protocol):
    """Per-channel base forecaster. Batch-trained, predicts covers."""

    def fit(self, X: np.ndarray, y: np.ndarray) -> None: ...
    def predict(self, X: np.ndarray) -> np.ndarray: ...
    def save(self, path: str) -> None: ...
    def load(self, path: str) -> None: ...


@runtime_checkable
class ResidualModel(Protocol):
    """Online residual learner. Updated per correction."""

    def predict(self, X: np.ndarray) -> np.ndarray: ...
    def update(self, X: np.ndarray, residual: np.ndarray) -> None: ...
    def warm_start(self, X: np.ndarray, residual: np.ndarray) -> None: ...
    def save(self, path: str) -> None: ...
    def load(self, path: str) -> None: ...
    @property
    def coefficients(self) -> dict[str, float]: ...
    @property
    def n_updates(self) -> int: ...
